name: Build

on:
  pull_request:
  push:
    paths:
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run all

    - uses: stefanzweifel/git-auto-commit-action@v4
